### ISSUE TITLE
review

### ISSUE THREAD

**Issue by Stapelzeiger** [CVRA-Aerospace/monitoring-module#1]

**Comment by Stapelzeiger** [comment]
- sdcard: DAT3 -> CS
- sdcard: nc pullup

**Comment by msplr** [comment]
Why do you place external pullups at the SPI?

**Comment by msplr** [comment]
Is the CAN_EN line really needed?

**Comment by Stapelzeiger** [comment]
> Why do you place external pullups at the SPI?

To avoid a potential SD card lockup when MCU is in reset.

CAN was removed to simplify PCB routing and reduce cost
